### ISSUE TITLE
As a developer, I want to be able to deploy code into 2 different environments so that I can distinguish between dev and prod.

### ISSUE THREAD

**Issue by porta-antiporta** [18F/uskpa#1]
The goal of this story is to set up our deployment pipeline from this repository to Heroku.  
Initially 2 environments (test and production) should suffice.
As for what is to be deployed, it'd be the application from #8.

Discuss in grooming:
* What are the URLs (can we deploy to test.uskpa.org and beta.uskpa.org without taking down uskpa.org.
* Control access to deploy to staging vs. production (is that baked into Heroku already?)

AC
* Able to see 2 instances of the app in 2 URLs
* Ensure setup / management of this deployment pipeline is documented in this repo.

**Comment by Jkrzy** [comment]
Closing this, PR #14 includes initial heroku setup allowing us to deploy to N locations and associated documentation on the two initial environments.
