### ISSUE TITLE
As an application deployed to test or production, I am able to send/receive emails so users can experience end to end functionality.

### ISSUE THREAD

**Issue by porta-antiporta** [18F/uskpa#21]
When running the application locally, mailhog simulates email service allowing the user to validate they are receiving expected emails.

However, when performing usability testing off the test environment, or in production itself proper, the system needs to access an email service to email out changes.

* The traffic will be minimal, on the order of 200/month (user registration, certificate updates). ** Discuss in grooming, what happens if a threshold is reached**
* For this engagement, email will only be outgoing to the user/subscribers; no incoming emails will be processed.

- [ ]  When app is run locally, mailhog is still functional
- [ ] When app is run on a cloud environment, emails are sent by the app and received in the users inbox
- [ ] Replies from users to those emails do not crash the app

**Comment by Jkrzy** [comment]
Resolved in #24
