### ISSUE TITLE
As an admin, I can create licensee organizations

### ISSUE THREAD

**Issue by porta-antiporta** [18F/uskpa#5]
Once authenticated admin can create licensees
* **Licensee (organization) Name** 
* **Address Line 1**
* Address Line 2
* **City**
* **State** 
* **Zipcode (5 digit)**
* Zipcode (4 digit)
* Primary contact (name)
* **Taxpayer ID**

Audit trail
* who : user
* type : licensee organization created
* record : licensee organization

**Comment by Jkrzy** [comment]
Added in PR #16
