### ISSUE TITLE
As an admin, I can create users

### ISSUE THREAD

**Issue by porta-antiporta** [18F/uskpa#7]
As an admin I can create users with the below fields.  
As part of creating the user I am able to set their password.  
The user is notified via email with their login information.

Fields
* **First name**
* **Last name**
* **Email**
* **Phone number**
* **Username** (set to same as Email)
* **Password**
* **Role** (minimum of 1)
   * Admin
   * Auditor
   * Licensee
       * Associated organization(s)

Ensure that this creation has an audit trail 
* who:  user
* type : create user
* record : user
* fields : values

**Comment by porta-antiporta** [comment]
Now that we have a basic Django set up (#8), `creating users` and setting their password has come for free.

This story then includes: 
* adding the additional fields above.
* setting up the email service 

Also note:  If Django treats username and email as the _same_ field, there's no need to change that at this moment.

**Comment by Jkrzy** [comment]
On the audit trail:

Can we assume that all user creation/changes will be performed via the website and as a result the audit trail can be managed within Django?

**Comment by porta-antiporta** [comment]
When you reference website, is that specifically the _admin_ portal or the uskpa website as well.

Creation would definitely be via the admin portal.
Changes, I can see a need for a user to be able to update their email or what not.  Does that come baked in as part of the default Django app, or do we need to code that in?

For this story, I'm more concerned with creating the users and notification to the users.  If _changes_ by the user is additional work, we can tackle that as part of a separate story.

**Comment by Jkrzy** [comment]
I was a bit too in the weeds on my earlier comment re: the audit trail specifically. I was thinking of changes being made via raw sql executed directly against the database. 

Maybe we should address that in another issue, as the implementation there will also cover the audit/change tracking for certificates, licensees, etc.

For this story, re-focusing on user creation/modification and email functionality.

Thanks!

**Comment by porta-antiporta** [comment]
Ah, let's put it this way.  We want to keep an audit trail of changes made via the website.

The intent is at the end of the engagement, there's no reason for anyone (including an admin) to write SQL statements to make changes to the data.

**Comment by Jkrzy** [comment]
@porta, PR merged in -- want to take a look at the functionality here before closing this out?

**Comment by porta-antiporta** [comment]
future Julian Porta, we meant @porta-antiporta

**Comment by Jkrzy** [comment]
Sorry for the errant `@` Julian Porta!!

No rush, thanks.

Just realized we're missing this piece: 
- [ ] The user is notified via email with their login information.

**Comment by Jkrzy** [comment]
PR #19 tackles the last piece here.

**Comment by porta-antiporta** [comment]
@Jkrzy a couple notes:

1. I'm not getting the email notification after I create an user from the admin tab (using mailinator and i tested the mailinator inbox was receiving emails).  Could very well be PEBKAC as I'm not sure if I need to set up mailhog separately.

2. Was a little disjointed to have First, Last, Email in one section `Personal Information` and Phone number in a separate section `Profile`.  How much effort is it to have them all in the same section?  (Checking to see if the juice is worth the squeeze before I ask for a change).

**Comment by Jkrzy** [comment]
Thanks @porta-antiporta! 

2. ~1 hour, we'd need to override the default Django admin html template in order to render the `Profile` fields among the other `User` fields. Django lets us specify the form order of fields on the `User` model but by default, it renders the related inline models like `Profile` at the end of the page.

**Comment by porta-antiporta** [comment]
1. Mailhog was working the entire time.  'Twas :pebkac:
2. Let's go ahead and make the change pls.  Can close this after that change is made.
